### ISSUE TITLE
MabelAPI does not catch bad URLs

### ISSUE THREAD

**Issue by CuriousJames** [CanterburyMedia/MabelCardPrinter#1]
I'm unable to work out how to catch an exception in the event a url call (as in MabelAPI.cs) returns no content, or cannot be resolved, should throw a MabelResponse.isError=true and exit out of the mabelApi class.

**Comment by naxxfish** [comment]
Can we define what a "good" response looks like? i.e. is 200 OK and some content good enough, or does it need to parse as well? 

Also we should probably throw an exception, rather than a valid object with a tag saying "this is an error", and handle those exceptions appropriately in the client classes

**Comment by CuriousJames** [comment]
A good response should always return an http status code of 2xx in the header, and meta->statusOK=true in the JSON returned to it.  Any invalid JSON returned, or a header without status 2xx should result in the code having a cool off period of say 30sec and then re-request the URL, and do this until a good result is returned.

Just so we're clear this is an example of a good json response that's returned:

> {"result":null,"meta":{"status":200,"statusOK":true,"msg":"OK","count":0}}

**Comment by naxxfish** [comment]
MabelAPI now offers much better Exception generating/handling capabilities.
